version: '3'

# Modern Taskfile with 2025 best practices

vars:
  BINARY_NAME: htmx-learn
  BUILD_DIR: ./tmp

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install all dependencies
    deps: [install-go-tools, install-tailwind]
    
  install-go-tools:
    desc: Install Go development tools
    cmds:
      - go install github.com/air-verse/air@latest
      - go install github.com/a-h/templ/cmd/templ@latest
    status:
      - which air
      - which templ

  install-tailwind:
    desc: Download Tailwind CSS standalone CLI
    cmds:
      - |
        if [ ! -f "./tailwindcss" ]; then
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          mv tailwindcss-linux-x64 tailwindcss
        fi
    status:
      - test -f "./tailwindcss"

  generate:
    desc: Generate templ templates
    cmds:
      - templ generate
    sources:
      - "templates/**/*.templ"
    generates:
      - "templates/**/*_templ.go"

  css:
    desc: Build CSS with Tailwind standalone CLI
    deps: [install-tailwind]
    cmds:
      - ./tailwindcss -i static/css/input.css -o static/css/output.css
    sources:
      - static/css/input.css
      - "templates/**/*.templ"
    generates:
      - static/css/output.css

  css-watch:
    desc: Watch and rebuild CSS
    deps: [install-tailwind]
    cmds:
      - ./tailwindcss -i static/css/input.css -o static/css/output.css --watch

  build:
    desc: Build the application
    deps: [generate, css]
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/{{.BINARY_NAME}}

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  dev:
    desc: Start development environment with live reload
    deps: [install]
    cmds:
      - task: dev-parallel

  dev-parallel:
    desc: Run development tasks in parallel
    deps: [generate]
    cmds:
      - |
        (
          # Start templ proxy for live reload
          templ proxy --url=http://localhost:8080 --port=7331 &
          
          # Start CSS watcher
          task css-watch &
          
          # Start Air for Go hot reload with inline config
          air \
            --build.cmd "go build -o tmp/htmx-learn ./cmd/htmx-learn" \
            --build.bin "./tmp/htmx-learn" \
            --build.delay "1000" \
            --build.exclude_dir "tmp,vendor,static" \
            --build.include_ext "go,templ" \
            --misc.clean_on_exit "true" &
          
          # Wait for all background processes
          wait
        )

  db-start:
    desc: Start PostgreSQL database using Docker Compose
    cmds:
      - docker-compose up postgres -d
      - echo "PostgreSQL database started"

  db-stop:
    desc: Stop PostgreSQL database
    cmds:
      - docker-compose stop postgres
      - echo "PostgreSQL database stopped"

  db-reset:
    desc: Reset database (WARNING: destroys all data)
    cmds:
      - docker-compose down postgres -v
      - docker-compose up postgres -d
      - echo "Database reset complete"

  db-logs:
    desc: View PostgreSQL database logs
    cmds:
      - docker-compose logs -f postgres

  db-shell:
    desc: Connect to PostgreSQL database shell
    cmds:
      - docker-compose exec postgres psql -U user -d htmx_learn

  db-backup:
    desc: Backup PostgreSQL database
    cmds:
      - mkdir -p backups
      - docker-compose exec postgres pg_dump -U user htmx_learn > backups/backup-$(date +%Y%m%d-%H%M%S).sql
      - echo "Database backed up to backups/"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f templates/**/*_templ.go
      - rm -f static/css/output.css

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - templ fmt .

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        else
          echo "golangci-lint not installed, skipping..."
        fi

  prod-build:
    desc: Build for production
    deps: [generate, css]
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./cmd/{{.BINARY_NAME}}